* Creating a library for proc_sql_Data;
libname procsql "/home/PATH/Proc_sql/data";

PROC SQL;
	SELECT *
	FROM PROCSQL.MANUFACTURERS;
QUIT;



***		BASIC CASE		**;
PROC SQL;
	SELECT MANUNAME,
			MANUSTAT,
			CASE MANUSTAT
				WHEN 'CA' THEN 'WEST'
				WHEN 'FL' THEN 'EAST'
				WHEN 'TX' THEN 'CENTRAL'
				ELSE 'UNKNOWN'
			END AS REGION
	FROM PROCSQL.MANUFACTURERS;
QUIT;


PROC SQL;
	SELECT PRODTYPE,
			CASE UPCASE(PRODTYPE)
				WHEN 'SOFTWARE' 	THEN 'SOFTWARE'
				WHEN 'PHONE'		THEN 'HARDWARE'
				WHEN 'LAPTOP'		THEN 'HARDWARE'
				WHEN 'WORKSTATION'	THEN 'HARDWARE'
				ELSE 'UNKNOWN'
			END AS PRODUCT_CLASSIFICATION
	FROM PROCSQL.PRODUCTS;
QUIT;



PROC SQL;
	SELECT 	PRODNAME,
			PRODCOST,
			CASE UPCASE(PRODTYPE) WHEN 'LAPTOP' THEN 1 ELSE 0 
					END AS LAPTOP_REQUEST,
			CASE UPCASE(PRODTYPE) WHEN 'PHONE' THEN 1 ELSE 0
					END AS PHONE_REQUEST,
			CASE UPCASE(PRODTYPE) WHEN 'WORKSTATION' THEN 1 ELSE 0
					END AS WORKSTATION_REQUEST,
			CASE UPCASE(PRODTYPE) WHEN 'SOFTWARE' THEN 1 ELSE 0
					END AS SOFTWARE_REQUEST
	FROM PROCSQL.PRODUCTS
QUIT;

