* Creating a library for proc_sql_Data;
libname procsql "/home/path/Proc_sql/data";

/** MANUFACTURING TABLE **/
PROC SQL;
	SELECT MANUCITY,
			MANUNAME,
			MANUNUM,
			MANUSTAT
	FROM PROCSQL.MANUFACTURERS;
QUIT;

/***		USING CONCATENATION OPERATOR		**/
PROC SQL;
	SELECT MANUCITY || ', ' || MANUSTAT
	FROM PROCSQL.MANUFACTURERS;
QUIT;



PROC SQL;
	SELECT CAT(MANUCITY, ', ', MANUSTAT)
	FROM PROCSQL.MANUFACTURERS;
QUIT;

** LENGTH OF THE STRING **;
PROC SQL;
	SELECT PRODNUM,
			PRODNAME,
			LENGTH(PRODNAME) AS LENGTH
	FROM PROCSQL.PRODUCTS;
QUIT;


** SCANNING A WORD **;
PROC SQL;
	SELECT PRODNAME,
			PRODTYPE,
			SCAN(PRODNAME,1) || ' ' ||TRIM(PRODTYPE) AS PRODUCT_DESCRIPTION
	FROM PROCSQL.PRODUCTS
	WHERE PRODTYPE IN ('Phone');
QUIT;


** TRIMMING THE SPACE **;
PROC SQL;
	SELECT LEFT(TRIM(MANUCITY) || ', ' ||MANUSTAT)
	FROM PROCSQL.MANUFACTURERS;
QUIT;


** ALIGNING TO RIGHT ***;
PROC SQL;
	SELECT RIGHT(MANUCITY)
	FROM PROCSQL.MANUFACTURERS;
QUIT;


** FINDING THE PATTERN USING INDEX ***;
PROC SQL;
	SELECT PRODNUM,
			PRODNAME,
			PRODTYPE
	FROM PROCSQL.PRODUCTS
	WHERE INDEX(PRODNAME, 'Phone') > 0;
QUIT;


** EXTRACTING INFORMATION FORM A STRING **;
PROC SQL;
	SELECT PRODNUM,
			PRODNAME,
			PRODTYPE,
			SUBSTR(PRODTYPE, 1, 4) AS INFO
	FROM PROCSQL.PRODUCTS
	WHERE PRODCOST > 100.0;
QUIT;
			

