* Creating a library for proc_sql_Data;
libname procsql "/home/PATH/Proc_sql/data";

*** 		DISPLAYING ROW NUMBER	**;
PROC SQL NUMBER;
	SELECT *
	FROM PROCSQL.INVOICE;
	QUIT;
	
** 	ASSIGNING FORMAT TO NUMBERS		**;
PROC SQL;
	SELECT PRODNAME,
			PRODTYPE,
			PRODCOST * 0.8 AS DISCOUNTED_PRICE FORMAT=DOLLAR9.2
	FROM PROCSQL.PRODUCTS
	ORDER BY 3;
QUIT;


**		CONCATENATING STRINGS	***;
PROC SQL;
	SELECT MANUCITY || MANUSTAT
	FROM PROCSQL.MANUFACTURERS;
QUIT;


PROC SQL;
	SELECT TRIM(MANUCITY) || ', ' || MANUSTAT AS HEADQUARTERS
	FROM PROCSQL.MANUFACTURERS;
QUIT;


***		CACULATED COLUMN	***;
PROC SQL;
	SELECT PRODNAME,
			PRODCOST,
			PRODCOST * 0.075 AS SALES_TAX FORMAT=DOLLAR9.2 LABEL='SALES TAX'
	FROM PROCSQL.PRODUCTS;
QUIT;


**		ORDERING THE RESULTS	***;
PROC SQL;
	SELECT *
	FROM PROCSQL.PRODUCTS
	ORDER BY PRODNAME;
QUIT;


PROC SQL;
	SELECT PRODNAME,
			PRODCOST,
			0.075 * PRODCOST AS SALES_TAX FORMAT=DOLLAR9.2 LABEL='SALES TAX'
	FROM PROCSQL.PRODUCTS
	ORDER BY 3;
QUIT;
	

***			MULTIPLE ORDERS			***;
PROC SQL NUMBER;
	SELECT PRODNAME,
			PRODTYPE,
			PRODCOST
	FROM PROCSQL.PRODUCTS
	ORDER BY PRODTYPE, PRODCOST DESC;
QUIT;








